internal enum MotionType
{
    WristUp,
    WristDown,
    DoubleWristUp,
    DoubleWristDown,
    TripleWristUp,
    TripleWristDown,
    IndexPull,
    IndexPush,
    DoubleIndexPull,
    ThumbPush,
    ThumbPull,
    RingPull,
    RingPush,
    DoubleRingPull,
    MiddlePull,
    MiddlePush,
};
