name: CubeTrainer
services:
  api:
    build: .
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=cubetrainer;Username=postgres;Password=postgres
    ports:
      - 5000:8080

  postgres:
    image: postgres:17.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 5

volumes:
  postgres-data:
